---
kind: pipeline
type: exec
name: Matrix Notifier check

steps:
- name: Pre-commit checks
  commands:
  - nix flake check

- name: Notifiy
  commands:
  - nix run .
  environment:
    ADDRESS:
      from_secret: matrix_homeserver
    ROOM:
      from_secret: matrix_roomid
    USER:
      from_secret: matrix_username
    PASS:
      from_secret: matrix_password
  when:
    status:
      - failure
      - success
...
